
document.addEventListener("DOMContentLoaded", addListeners);
var intervalCodeData = {};
var intervalIndex = 0;

var begin = 0;
var end = 0;

var next = null;
var prev = null;

// This is loading the history of which pages came from what searches (generated by visitStats.py)
// This info will then be used to chance the appearance of repeat visits and visits not generated by
// current search
var searchHistory = {}
fetch("/data/repeatVisits.json")
.then(response => {
   return response.json();
})
.then(jsondata => {
    // console.log("JSON DATA" + JSON.stringify(jsondata));
    searchHistory = jsondata;
    return jsondata;
});


function addListeners() {
    console.log("document loaded...");
    addWebEpisode();

    const accordion = document.getElementsByClassName('label');

    // console.log("adding listeners to " + accordion.length + ": " + accordion);
    for (i=0; i<accordion.length; i++) {
    accordion[i].addEventListener('click', function () {
            console.log(this.parentElement);
            this.parentElement.classList.toggle('active')
        })
    }

    next = document.getElementById("nextCode");
    prev = document.getElementById("previousCode");

    if (next != null) {
        next.addEventListener('click', showNextCode);
    }
    if (prev != null) {
        prev.addEventListener('click', showPreviousCode);
    }

    // console.log("next code: " + next);
    // console.log("prev code" + prev);
}

function disableButtons() {
    if (intervalIndex == intervalCodeData.length -1) {
        next.disabled = true;
    } else {
        next.disabled = false;
    }
    if (intervalIndex == 0) {
        prev.disabled = true;
    } else {
        prev.disabled = false;
    }
}

function showNextCode() {
    console.log("show next");
    if (intervalIndex < intervalCodeData.length-1) {
        intervalIndex = intervalIndex + 1;
    }
    disableButtons();
   

    console.log("interval is " + intervalIndex);
    updateCodeInfo(intervalCodeData[intervalIndex])
}

function showPreviousCode() {
    console.log("show previous");
    if (intervalIndex > 0) {
        intervalIndex = intervalIndex - 1;
    }
    disableButtons();
   
    console.log("interval is " + intervalIndex);
    updateCodeInfo(intervalCodeData[intervalIndex])
}

function setIntervalCodeData(beginTime, endTime, data) {
    begin = beginTime;
    end = endTime;

    intervalCodeData = data;
    intervalIndex = intervalCodeData.length -1;
    disableButtons();
    console.log("interval CODE data " + intervalCodeData[intervalIndex]);
    updateCodeInfo(intervalCodeData[intervalIndex]);
}

function setIntervalSearchData(beginTime, endTime, data) {
    begin = beginTime;
    end = endTime;

    intervalSearchData = data;
    console.log("interval SEARCH data " + intervalSearchData[intervalIndex]);
    updateSearchInfo(intervalSearchData);
}

function seek(time) {
    seekTo(time);
    return false;
}

function updateSearchInfo(searchData) {
    console.log("");
    console.log(searchData);
    console.log("");
    console.log("");
    var html = ""
    var openSearch = false;
    var currentSearch = "";
    for (var i = 0; i < searchData.length; i++) {
        // console.log(i + ": " + searchData[i]["notes"])
        var endOfType = searchData[i]["notes"].indexOf(":");
        var endOfDesc = searchData[i]["notes"].indexOf(";");

        if (endOfDesc < 0) {
            endOfDesc = searchData[i]["notes"].length;
        }
        
        if (endOfType > 0) {
            var desc = searchData[i]["notes"].substring(endOfType + 1, endOfDesc);
            var navType = searchData[i]["notes"].substring(0, searchData[i]["notes"].indexOf(":"))

            if (navType == "search") {
                //var codeHeader = "<span>" + begin + " - " + end + "(@<a href='javascript:' onclick='seek(" +currentData["time"] +")'>" + currentData["time"] + "</a>)</span>"
                console.log("SEARCH: " + i + "<a href='javascript:' onclick='seek(" +searchData[i]["time"] +")'>" + desc + "</a>" );
                if (openSearch) {
                    html += "</div>" // close the previous imageRow
                } 
                html += getSearchTitle(searchData[i]["time"], desc);
                html += "<div class='webImageRow'>"; // this opens up an imageRow
                openSearch = true;
                currentSearch = desc;
            } else if (navType.indexOf("visit") >= 0) {
                console.log("\t" + i + ": " + navType + " " + desc);
                if (openSearch) {
                    html += getImageTable(searchData[i]["img_file"], desc, currentSearch);
                } else {
                    openSearch = true;
                    currentSearch="";
                    html += getSearchTitle(searchData[i]["time"], "Past Searches");
                    html += "<div class='webImageRow'>"; // this opens up an imageRow
                    html += getImageTable(searchData[i]["img_file"], desc, currentSearch);
                }
            } else {
                console.log("\t ignoring " + navType )
            }
        } else {
            console.log("NO type: " + searchData[i]["notes"]);
        }
    }

    if (openSearch) html +=  "</div>" // close the previous imageRow;

    // console.log(html);

    const webAccordion = document.getElementById('search_container');
    // console.log("webAccordion " + webAccordion);
    webAccordion.innerHTML = html;

}

function updateCodeInfo(currentData){
    console.log("current data " + currentData);

    if (currentData) {

        var currCode = "<code style='white-space: pre'>" + currentData["code_text"] + "</code>";
        document.getElementById("code_content").innerHTML = currCode;

        var codeHeader = "<span>" + begin + " - " + end + "(@<a href='javascript:' onclick='seek(" +currentData["time"] +")'>" + currentData["time"] + "</a>)</span>"
        document.getElementById("code_header").innerHTML = codeHeader
    } else {

        var currCode = "<code style='white-space: pre'>" + "No Code.</code>";
        document.getElementById("code_content").innerHTML = currCode;

        var codeHeader = "<span>" + begin + " - " + end + "(@<a href='javascript:' onclick='seek(" + end +")'>" + end + "</a>)</span>"
        document.getElementById("code_header").innerHTML = codeHeader
    }
}

function getImageTable(filename, description, search) {
    // style="border:1px solid black" this will add a border around to show that it's repeat information.

    var recordedSearch = ""
    if (description in searchHistory) {
        recordedSearch = searchHistory[description]["search"];
    }

    console.log("search is" + search + " -> " + recordedSearch + (search == recordedSearch))

    var border= ""
    // so search can be one of two things "" basically undefined, meaning that this has to be a revisit to a past search
    if (recordedSearch == "") {
        console.log("empty search -> repeat visit")
        border = "style='border:1px solid black'"
    } else {
        // or it can have a value. if the value is the same as the owner search and its a revisited page, then this is a close revisit.
        if (recordedSearch == search) {
            if  (searchHistory[description]["count"]>1) {
                console.log("same search -> close visit")
                border = "style='border:1px solid lightgray'"
            }
        } else {
            // if the current one search is differen than the owner search, this is a far revisit.
            console.log("diff search -> far visit")
            border = "style='border:1px solid black'"
        }
    }
    
    console.log("current " + search + " recorded " + recordedSearch);

    var table = "<div class='webImage' " + border + "> <table>" 
    + "<tr><td><img src='/images/foodNotFood/" + filename + "' width='180' height='112'> </td></tr>" 
    + "<tr><td>" + description + "</td></tr></table></div>"

    return table;
}

function getSearchTitle(time, title) {
    // console.log("SEARCH: " + i + "<a href='javascript:' onclick='seek(" +searchData[i]["time"] +")'>" + desc + "</a>" );
    var html = "<div class='webTitle'><span><a href='javascript:' onclick='seek(" + time + ")'>" + title + "</a></span></div><hr>";
    return html;
}

function getSearchUI(searchTitle) {
    var html = getSearchTitle(searchTitle);

    html = html + "<div class='webImageRow'>"
    html = html + getImageTable("screencapture-localhost-8000-2022-01-20-11_26_30.png", "This is where the text goes");
    html = html + getImageTable("screencapture-localhost-8000-2022-01-20-11_26_30.png", "This is where the next text goes. It's a longer description.");
    html = html + getImageTable("screencapture-localhost-8000-2022-01-20-11_26_30.png", "And here is another one.");
    html = html + "</div>"

    return html;
}

function addWebEpisode() {
    const webAccordion = document.getElementById('search_container');
    // console.log("webAccordion " + webAccordion);

    if (webAccordion != null) {

        var search = "This is the title for a search.";

        var html = getSearchUI(search);
        html = html + getSearchUI(search);

        webAccordion.innerHTML = html;
    }
}